:l T13825
let packed2 = Packed 2.0 3.0 4 5 6 7
let ghciAddOne (Packed a b c d e f) = Packed (a + 1.0) (b + 1.0) (c + 1) (d + 1) (e + 1.0) (f + 1)
modAddOne packed1
modAddOne packed2
ghciAddOne packed1
ghciAddOne packed2

:set -fobject-code
:l T13825
:set -fbyte-code
let packed2 = Packed 2.0 3.0 4 5 6 7
let ghciAddOne (Packed a b c d e f) = Packed (a + 1.0) (b + 1.0) (c + 1) (d + 1) (e + 1.0) (f + 1)
modAddOne packed1
modAddOne packed2
ghciAddOne packed1
ghciAddOne packed2
